tests: util: use _internal_id_ids_cb instead _filename_ids_cb
Since we started using pathlib _filename_ids_cb returns PosixPath but
pytest.mark.parametrize requires string, int, float, bool, or None.

Newer pytest is able to ignore the incorrect return value and instead it
generates numeric ID so the resulting id is `devicexml01`. Older
pytest fails with exception:

    AttributeError: 'PosixPath' object has no attribute 'encode'

Signed-off-by: Pavel Hrdina <phrdina@redhat.com>