tests: util: use _shortid_ids_cb in platform_parametrize
Since we started using pathlib _filename_ids_cb returns PosixPath but
pytest.mark.parametrize requires string, int, float, bool, or None.

Newer pytest is able to ignore the incorrect return value and instead it
generates numeric ID so the resulting id is `platformxml01`. Older
pytest fails with exception:

    AttributeError: 'PosixPath' object has no attribute 'encode'

Signed-off-by: Pavel Hrdina <phrdina@redhat.com>